matrix:
  allow_failures:
    dart: "1.24.3"

  - language: dart
    dart:
    - stable
    - dev
    - "1.24.3"
    dart_task:
    - dartanalyzer: --fatal-warnings --no-implicit-casts --no-implicit-dynamic .
    - dartfmt --dry-run --set-exit-if-changed lib/*.dart bin/*.dart

  - language: cpp
    script: make --directory=lib
