language: dart

dart:
- stable
- dev
- "1.24.3"

dart_task:
# - test
- dartanalyzer: --no-implicit-casts .
- dartfmt --dry-run --set-exit-if-changed lib/*.dart bin/*.dart

matrix:
  allow_failures:
    - dart: "1.24.3"
