name: curses
version: 0.1.0
author: Iván Zaera Avellón <izaera@gmail.com>
description: Bindings for curses library in Dart
homepage: https://github.com/izaera/dart-curses
environment:
  sdk: '>=0.8.10+6 <=2.2.0'
dependencies:
  logging: any
