name: curses
version: 0.2.0
author: Iván Zaera Avellón <izaera@gmail.com>
description: Bindings for curses library in Dart
homepage: https://github.com/izaera/dart-curses
environment:
  sdk: '>=1.24.3 <3.0.0'
dependencies:
  logging: any
